name: seal-build

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "12"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: devalue-tgz
          path: devalue-*.tgz
          if-no-files-found: error
